import { useSettingsStore } from "../stores/settings.js";

// Backwards-compatible plain helper (non-reactive, for non-template use).
// For reactive template use, prefer the composable useTranslateUi() below.

const UI_TRANSLATIONS = {
  // Categories
  "text & content": "អត្ថបទ និងខ្លឹមសារ",
  "layout": "ប្លង់",
  "info blocks": "ប្លុកព័ត៌មាន",
  "document": "ឯកសារ",
  "financial": "ហិរញ្ញវត្ថុ",
  "footer": "ផ្នែកខាងក្រោម",
  "print": "បោះពុម្ព",
  "mobile / receipt": "ទូរស័ព្ទ / បង្កាន់ដៃ",

  // Block Names
  "text": "អត្ថបទ",
  "dynamic text": "អត្ថបទឌីណាមិក",
  "image": "រូបភាព",
  "divider": "បន្ទាត់ខណ្ឌ",
  "spacer": "ចន្លោះ",
  "shape": "រូបរាង",
  "container": "ប្រអប់ផ្ទុក",
  "row": "ជួរដេក",
  "column": "ជួរឈរ",
  "grid": "ក្រឡាចត្រង្គ",
  "section": "ផ្នែក",
  "background": "ផ្ទៃខាងក្រោយ",
  "page break": "ផ្តាច់ទំព័រ",
  "page number": "លេខទំព័រ",
  "company info": "ព័ត៌មានក្រុមហ៊ុន",
  "client info": "ព័ត៌មានអតិថិជន",
  "header grid": "ក្រឡាចត្រង្គក្បាលទំព័រ",
  "field row": "ជួរវាលព័ត៌មាន",
  "document title": "ចំណងជើងឯកសារ",
  "document number": "លេខឯកសារ",
  "issue date": "កាលបរិច្ឆេទចេញ",
  "due date": "ថ្ងៃកំណត់បង់",
  "reference no.": "លេខយោង",
  "notes": "កំណត់សម្គាល់",
  "terms & conditions": "លក្ខខណ្ឌផ្សេងៗ",
  "footer note": "កំណត់សម្គាល់បាតទំព័រ",
  "thank you": "សូមអរគុណ",
  "item table": "តារាងទំនិញ",
  "table builder": "អ្នកបង្កើតតារាង",
  "totals block": "ប្លុកសរុប",
  "currency summary": "សេចក្តីសង្ខេបរូបិយប័ណ្ណ",
  "amount in words": "ទឹកប្រាក់ជាអក្សរ",
  "subtotal": "សរុបរង",
  "discount": "បញ្ចុះតម្លៃ",
  "tax / vat": "អាករ / VAT",
  "grand total": "សរុបរួម",
  "balance due": "ប្រាក់ត្រូវទូទាត់",
  "deposit / paid": "ប្រាក់កក់ / បានបង់",
  "bank details": "ព័ត៌មានធនាគារ",
  "signature line": "បន្ទាត់ហត្ថលេខា",
  "digital signature": "ហត្ថលេខាឌីជីថល",
  "variable binding": "ការភ្ជាប់អថេរ",
  "repeat block": "ប្លុកសារឡើងវិញ",
  "conditional block": "ប្លុកមានលក្ខខណ្ឌ",
  "formula": "រូបមន្ត",
  "barcode": "បាកូដ",
  "multi-language": "ពហុភាសា",
  "watermark": "រូបសម្គាល់ទឹក",
  "scanner result": "លទ្ធផលស្កែន",
  "document header": "ក្បាលឯកសារ",
  "checkboxes row": "ជួរប្រអប់ធីក",
  "table": "តារាង",
  "stamp box": "ប្រអប់វាយត្រា",
  "cut line": "បន្ទាត់កាត់",
  "carbon copy label": "ស្លាកច្បាប់ចម្លង",
  "receipt header": "ក្បាលបង្កាន់ដៃ",
  "receipt footer": "បាតបង្កាន់ដៃ",

  // Block Descriptions
  "static text, any style": "អត្ថបទឋិតិវន្ត ស្ទីលណាក៏បាន",
  "{{variable}} placeholder": "កន្លែងបំពេញ {{variable}}",
  "upload logo, stamp, qr image": "បង្ហោះឡូហ្គោ ត្រា ឬរូបភាព QR",
  "horizontal line": "បន្ទាត់ផ្ដេក",
  "vertical gap": "គម្លាតបញ្ឈរ",
  "rectangle, circle, line": "ចតុកោណកែង រង្វង់ ឬបន្ទាត់",
  "group blocks together": "ក្រុមប្លុកបញ្ចូលគ្នា",
  "horizontal flex layout": "ប្លង់ផ្ដេកបត់បែន",
  "vertical layout": "ប្លង់បញ្ឈរ",
  "multi-column grid": "ក្រឡាចត្រង្គច្រើនជួរឈរ",
  "reusable grouped layout": "ប្លង់ក្រុមដែលអាចប្រើឡើងវិញបាន",
  "colored section background": "ផ្ទៃខាងក្រោយផ្នែកដែលមានពណ៌",
  "force new page in pdf": "បង្ខំទំព័រថ្មីក្នុង PDF",
  "auto page numbering": "ការដាក់លេខទំព័រស្វ័យប្រវត្តិ",
  "logo + name + address + contact": "ឡូហ្គោ + ឈ្មោះ + អាសយដ្ឋាន + ទំនាក់ទំនង",
  "name + address + contact": "ឈ្មោះ + អាសយដ្ឋាន + ទំនាក់ទំនង",
  "multi-column info grid, fill mode": "ក្រឡាចត្រង្គព័ត៌មានច្រើនជួរឈរ",
  "label + value pair": "គូ ស្លាក + តម្លៃ",
  "invoice / receipt heading": "ចំណងជើង វិក្កយបត្រ / បង្កាន់ដៃ",
  "auto invoice number": "លេខវិក្កយបត្រស្វ័យប្រវត្តិ",
  "date with format options": "កាលបរិច្ឆេទជាមួយជម្រើសទម្រង់",
  "due date with overdue highlight": "ថ្ងៃកំណត់បង់ជាមួយការរំលេចការហួសកំណត់",
  "po or custom reference": "PO ឬលេខយោងផ្ទាល់ខ្លួន",
  "free text notes area": "កន្លែងសរសេរកំណត់សម្គាល់សេរី",
  "scrollable terms text": "អត្ថបទលក្ខខណ្ឌដែលអាចរំកិលបាន",
  "small print at bottom": "អត្ថបទតូចនៅផ្នែកខាងក្រោម",
  "styled closing message": "សារបញ្ចប់ដ៏ស្រស់ស្អាត",
  "line items with configurable columns": "ទំនិញនីមួយៗជាមួយជួរឈរដែលអាចកំណត់បាន",
  "fully custom column table": "តារាងជួរឈរតាមបំណងទាំងស្រុង",
  "subtotal, tax, grand total": "សរុបរង ពន្ធ សរុបរួម",
  "multi-currency breakdown": "ការវិភាគរូបិយប័ណ្ណច្រើនប្រភេទ",
  "\"five dollars only\"": "«ប្រាំដុល្លារគត់»",
  "auto sum of line items": "ផលបូកស្វ័យប្រវត្តិនៃទំនិញ",
  "fixed or percentage discount": "ការបញ្ចុះតម្លៃថេរ ឬជាភាគរយ",
  "configurable tax rate": "អត្រាអាករដែលអាចកំណត់បាន",
  "bold styled final amount": "ទឹកប្រាក់ចុងក្រោយស្ទីលដិត",
  "remaining unpaid amount": "ទឹកប្រាក់ដែលនៅសល់មិនទាន់បង់",
  "amount already paid": "ទឹកប្រាក់ដែលបានបង់រួចហើយ",
  "bank name, account info": "ឈ្មោះធនាគារ ព័ត៌មានគណនី",
  "signature line + label": "បន្ទាត់ហត្ថលេខា + ស្លាក",
  "placeholder for digital sig": "កន្លែងសម្រាប់ហត្ថលេខាឌីជីថល",
  "{{customer.name}} binding": "ការភ្ជាប់ {{customer.name}}",
  "loop over data array": "រង្វិលជុំលើអារេដាទា",
  "show/hide on condition": "បង្ហាញ/លាក់ តាមលក្ខខណ្ឌ",
  "custom calculation formula": "រូបមន្តគណនាផ្ទាល់ខ្លួន",
  "product or document barcode": "បាកូដផលិតផល ឬឯកសារ",
  "khmer + english side by side": "ភាសាខ្មែរ + អង់គ្លេស ទន្ទឹមគ្នា",
  "diagonal text or image overlay": "អត្ថបទអង្កត់ទ្រូង ឬរូបភាពត្រួតលើគ្នា",
  "display qr scan result as text": "បង្ហាញលទ្ធផលស្កែន QR ជាអត្ថបទ",
  "title + number + date + reference": "ចំណងជើង + លេខ + កាលបរិច្ឆេទ + យោង",
  "☐ cash  ☐ transfer  ☐ credit": "☐ សាច់ប្រាក់  ☐ ផ្ទេរប្រាក់  ☐ ឥណទាន",
  "☐ cash ☐ transfer ☐ credit": "☐ សាច់ប្រាក់ ☐ ផ្ទេរប្រាក់ ☐ ឥណទាន",
  "rows + columns, fully configurable": "ជួរដេក + ជួរឈរ អាចកំណត់រចនាសម្ព័ន្ធបានទាំងស្រុង",
  "empty box for rubber stamp": "ប្រអប់ទទេសម្រាប់វាយត្រាកៅស៊ូ",
  "✂ dashed separation line": "✂ បន្ទាត់ដាច់ៗសម្រាប់ខណ្ឌកាត់",
  "original / copy 1 / copy 2": "ច្បាប់ដើម / ច្បាប់ចម្លងទី ១ / ច្បាប់ចម្លងទី ២",
  "shop name, address, phone": "ឈ្មោះហាង អាសយដ្ឋាន ទូរស័ព្ទ",
  "thank you + return policy": "សូមអរគុណ + គោលការណ៍ត្រឡប់មកវិញ",

  // Inspector Panel / General UI
  "block library": "បណ្ណាល័យប្លុក",
  "inspector": "កម្មវិធីត្រួតពិនិត្យ",
  "no block selected": "មិនមានប្លុកត្រូវបានជ្រើសរើសទេ",
  "select a block on the canvas to inspect and edit its properties.": "ជ្រើសរើសប្លុកនៅលើផ្ទាំងការងារ ដើម្បីត្រួតពិនិត្យ និងកែសម្រួលលក្ខណៈសម្បត្តិរបស់វា។",
  "unlock block": "ដោះសោប្លុក",
  "lock block": "ចាក់សោប្លុក",
  "duplicate block": "ចម្លងប្លុក",
  "bring forward": "នាំមកមុខ",
  "send backward": "ផ្ញើទៅក្រោយ",
  "delete block": "លុបប្លុក",
  "style": "រចនាបថ",
  "data": "ទិន្នន័យ",
  "block": "ប្លុក",
  "responsive": "ភាពបត់បែន",
  "history": "ប្រវត្តិ",
  "position & size": "ទីតាំង និងទំហំ",
  "x position": "ទីតាំង X",
  "y position": "ទីតាំង Y",
  "width": "ទទឹង",
  "height": "កម្ពស់",
  "padding": "ចន្លោះខាងក្នុង",
  "padding top": "ចន្លោះខាងលើ",
  "padding bottom": "ចន្លោះខាងក្រោម",
  "padding left": "ចន្លោះខាងឆ្វេង",
  "padding right": "ចន្លោះខាងស្តាំ",
  "margin": "ចន្លោះខាងក្រៅ",
  "margin top": "ចន្លោះខាងក្រៅខាងលើ",
  "margin bottom": "ចន្លោះខាងក្រៅខាងក្រោម",
  "display": "ការបង្ហាញ",
  "visible on screen": "បង្ហាញលើអេក្រង់",
  "hide in pdf": "លាក់ក្នុង PDF",
  "align": "តម្រឹម",
  "fill & background": "ពណ៌ផ្ទៃ និងផ្ទៃខាងក្រោយ",
  "background color": "ពណ៌ផ្ទៃខាងក្រោយ",
  "border width": "កម្រាស់ស៊ុម",
  "border style": "ម៉ូតស៊ុម",
  "border color": "ពណ៌ស៊ុម",
  "border radius": "កោងជ្រុង",
  "solid": "ស៊ុមជាប់",
  "dashed": "ស៊ុមដាច់ៗ",
  "dotted": "ស៊ុមចុចៗ",
  "shadow": "ស្រមោល",
  "shadow blur": "ស្រមោលព្រិល",
  "shadow color": "ពណ៌ស្រមោល",
  "typography": "អក្សរសាស្ត្រ",
  "font family": "ប្រភេទពុម្ពអក្សរ",
  "font size": "ទំហំអក្សរ",
  "font weight": "កម្រាស់អក្សរ",
  "line height": "កម្ពស់ជួរ",
  "text color": "ពណ៌អក្សរ",
  "text align": "តម្រឹមអត្ថបទ",
  "alignment": "ការតម្រឹម",
  "style & decoration": "រចនាបថ និងការតុបតែង",
  "underline": "គូសបន្ទាត់ក្រោម",
  "strikethrough": "គូសបន្ទាត់ចំកណ្តាល",
  "use global font": "ប្រើប្រាស់ពុម្ពអក្សររួម",
  "format visibility": "ភាពអាចមើលឃើញតាមទម្រង់",
  "choose which paper formats this block should be visible on. if a format is disabled, this block will be hidden when that format is active.": "ជ្រើសរើសទម្រង់ក្រដាសដែលត្រូវបង្ហាញប្លុកនេះ។ ប្រសិនបើបិទទម្រង់ណាមួយ ប្លុកនេះនឹងត្រូវលាក់នៅពេលទម្រង់នោះសកម្ម។",
  "a4 page": "ទំព័រ A4",
  "a5 page": "ទំព័រ A5",
  "58mm receipt": "បង្កាន់ដៃ ៥៨មម",
  "80mm receipt": "បង្កាន់ដៃ ៨០មម",
  "history management": "ការគ្រប់គ្រងប្រវត្តិ",
  "undo or redo recently made changes. the builder stores up to 50 edits.": "សារដើម ឬសារឡើងវិញនូវការផ្លាស់ប្តូរថ្មីៗ។ កម្មវិធីរក្សាទុកការកែប្រែរហូតដល់ ៥០ដង។",
  "clear canvas template": "សម្អាតផ្ទាំងការងារ",
  "clear canvas": "សម្អាតផ្ទាំងការងារ",
  "are you sure you want to clear the entire canvas? this cannot be undone.": "តើអ្នកប្រាកដជាចង់សម្អាតផ្ទាំងការងារទាំងមូលមែនទេ? ការធ្វើបែបនេះមិនអាចយកវិញបានទេ។",
  "clear all": "សម្អាតទាំងអស់",
  "keyboard shortcuts": "គ្រាប់ចុចផ្លូវកាត់",
  "table data": "ទិន្នន័យតារាង",
  "edit rows, quantities, and prices directly in the table on the canvas.": "កែសម្រួលជួរដេក បរិមាណ និងតម្លៃដោយផ្ទាល់នៅក្នុងតារាងនៅលើផ្ទាំងការងារ។",
  "use right-click context menu on cell, row numbers, or column headers to insert, delete, or merge cells and rows.": "ប្រើម៉ឺនុយចុចខាងស្តាំលើក្រឡា លេខជួរដេក ឬក្បាលជួរឈរ ដើម្បីបញ្ចូល លុប ឬច្របាច់ក្រឡានិងជួរដេក។",
  "auto calculation": "ការគណនាស្វ័យប្រវត្តិ",
  "totals are automatically calculated from the item table on this canvas. adjust tax rate and discount settings in the block tab.": "ចំនួនសរុបត្រូវបានគណនាដោយស្វ័យប្រវត្តិតាមរយៈតារាងទំនិញនៅលើផ្ទាំងការងារនេះ។ លៃតម្រូវអត្រាអាករ និងការបញ្ចុះតម្លៃនៅក្នុងផ្ទាំង «ប្លុក»។",
  "subtotal, tax and grand total update live as you edit items.": "សរុបរង អាករ និងសរុបរួម នឹងធ្វើបច្ចុប្បន្នភាពផ្ទាល់ភ្លាមៗនៅពេលអ្នកកែសម្រួលទំនិញ។",
  "select an item table block to manage rows, or a totals block to see calculation info.": "ជ្រើសរើសប្លុកតារាងទំនិញ ដើម្បីគ្រប់គ្រងជួរដេក ឬប្លុកសរុប ដើម្បីមើលព័ត៌មានគណនា។",
  "block properties": "លក្ខណៈសម្បត្តិប្លុក",

  // Tab text labels / properties
  "label width %": "ទទឹងស្លាក %",
  "left indent": "ចូលបន្ទាត់ឆ្វេង",
  "right indent": "ចូលបន្ទាត់ស្តាំ",
  "top padding": "ចន្លោះខាងលើ",
  "bottom padding": "ចន្លោះខាងក្រោម",
  "text content": "ខ្លឹមសារអត្ថបទ",
  "alignment & color": "តម្រឹម និងពណ៌",
  "label": "ស្លាក",
  "value": "តម្លៃ",
  "placeholder": "អត្ថបទជំនួយ",
  "format": "ទម្រង់",
  "date format": "ទម្រង់កាលបរិច្ឆេទ",
  "overdue alert": "ការជូនដំណឹងហួសកំណត់",
  "notes block content": "ខ្លឹមសារប្លុកកំណត់សម្គាល់",
  "terms block content": "ខ្លឹមសារប្លុកលក្ខខណ្ឌផ្សេងៗ",
  "signature label": "ស្លាកហត្ថលេខា",
  "show line": "បង្ហាញបន្ទាត់",
  "logo image": "រូបភាពឡូហ្គោ",
  "upload image": "បង្ហោះរូបភាព",
  "image width": "ទទឹងរូបភាព",
  "image height": "កម្ពស់រូបភាព",
  "fill mode (stretched)": "របៀបបំពេញ (ទាញពន្លាត)",
  "company name": "ឈ្មោះក្រុមហ៊ុន",
  "company details": "ព័ត៌មានលម្អិតក្រុមហ៊ុន",
  "show email": "បង្ហាញអ៊ីមែល",
  "show phone": "បង្ហាញលេខទូរស័ព្ទ",
  "show website": "បង្ហាញគេហទំព័រ",
  "client name": "ឈ្មោះអតិថិជន",
  "client details": "ព័ត៌មានលម្អិតអតិថិជន",
  "barcode value": "តម្លៃបាកូដ",
  "barcode format": "ទម្រង់បាកូដ",
  "display value": "បង្ហាញអក្សរក្រោមបាកូដ",
  "header columns": "ជួរឈរក្បាលទំព័រ",
  "show document title": "បង្ហាញចំណងជើងឯកសារ",
  "show document number": "បង្ហាញលេខឯកសារ",
  "show issue date": "បង្ហាញកាលបរិច្ឆេទចេញ",
  "show due date": "បង្ហាញថ្ងៃកំណត់បង់",
  "show reference number": "បង្ហាញលេខយោង",
  "totals styling": "រចនាបថចំនួនសរុប",
  "discount rate %": "អត្រាបញ្ចុះតម្លៃ %",
  "discount value": "តម្លៃបញ្ចុះតម្លៃ",
  "tax rate %": "អត្រាអាករ %",
  "currency code": "កូដរូបិយប័ណ្ណ",
  "decimal places": "ចំនួនខ្ទង់ក្បៀស",
  "checkbox option options": "ជម្រើសប្រអប់ធីក",
  "options": "ជម្រើស",
  "watermark text": "អត្ថបទសម្គាល់ទឹក",
  "opacity": "ភាពស្រអាប់",
  "rotation": "ការបង្វិល",
  "cut line style": "រចនាបថបន្ទាត់កាត់",
  "dashed line": "បន្ទាត់ដាច់ៗ",
  "solid line": "បន្ទាត់ជាប់",
  "scissor icon": "រូបភាពកន្ត្រៃ",
  "carbon copy details": "ព័ត៌មានលម្អិតច្បាប់ចម្លង",
  "receipt name": "ឈ្មោះហាងបង្កាន់ដៃ",
  "receipt details": "ព័ត៌មានលម្អិតបង្កាន់ដៃ",
  "show receipt logo": "បង្ហាញឡូហ្គោបង្កាន់ដៃ",
  "receipt logo image": "រូបភាពឡូហ្គោបង្កាន់ដៃ",
  "receipt footer text": "អត្ថបទបាតបង្កាន់ដៃ",
  "show return policy": "បង្ហាញគោលការណ៍ត្រឡប់មកវិញ",
  "return policy text": "អត្ថបទគោលការណ៍ត្រឡប់មកវិញ",
  "column settings": "ការកំណត់ជួរឈរ",
  "add column": "បន្ថែមជួរឈរ",
  "table outline": "ស៊ុមក្រៅតារាង",
  "show table borders": "បង្ហាញបន្ទាត់ស៊ុមតារាង",
  "show table header": "បង្ហាញក្បាលតារាង",
  "header background": "ផ្ទៃខាងក្រោយក្បាលតារាង",
  "header text color": "ពណ៌អក្សរក្បាលតារាង",
  "font weight bold": "អក្សរដិតខ្លាំង",
  "border style double": "ស៊ុមពីរជាន់",
  "amount in words content": "ខ្លឹមសារទឹកប្រាក់ជាអក្សរ",
  "prefix text": "អក្សរខាងមុខ",
  "suffix text": "អក្សរខាងក្រោយ",
  "use uppercase": "ប្រើអក្សរធំ",
  "totals layout & currency": "ប្លង់ចំនួនសរុប និងរូបិយប័ណ្ណ",
  "visible fields": "វាលដែលអាចមើលឃើញ",
  "show subtotal": "បង្ហាញសរុបរង",
  "show discount": "បង្ហាញការបញ្ចុះតម្លៃ",
  "show tax": "បង្ហាញអាករ",
  "show grand total": "បង្ហាញសរុបរួម",
  "show balance due": "បង្ហាញប្រាក់ត្រូវទូទាត់",
  "show deposit / paid": "បង្ហាញប្រាក់កក់ / បានបង់",
  "layout settings": "ការកំណត់ប្លង់",
  "spacing": "គម្លាត",
  "inner gap": "គម្លាតខាងក្នុង",
  "align items": "តម្រឹមធាតុ",
  "justify content": "តម្រឹមខ្លឹមសារ",
  "start": "ចាប់ផ្តើម",
  "center": "កណ្តាល",
  "end": "បញ្ចប់",
  "space-between": "ចន្លោះកណ្តាលស្មើគ្នា",
  "space-around": "ចន្លោះជុំវិញស្មើគ្នា",
  "space-evenly": "ចន្លោះស្មើគ្នាទាំងអស់",
  "text size": "ទំហំអត្ថបទ",
  "text style": "រចនាបថអត្ថបទ",
  "shape settings": "ការកំណត់រូបរាង",
  "shape type": "ប្រភេទរូបរាង",
  "rectangle": "ចតុកោណកែង",
  "circle": "រង្វង់",
  "line": "បន្ទាត់",
  "fill color": "ពណ៌ផ្ទៃរូបរាង",
  "container settings": "ការកំណត់ប្រអប់ផ្ទុក",
  "layout type": "ប្រភេទប្លង់",
  "flex row": "Flex ជួរដេក",
  "flex column": "Flex ជួរឈរ",
  "absolute positioning": "ទីតាំងកំណត់ច្បាស់លាស់ (Absolute)",
  "overflow hidden": "លាក់ខ្លឹមសារលើសហៀរ",
  "align-start": "តម្រឹមខាងដើម",
  "align-center": "តម្រឹមចំកណ្តាល",
  "align-end": "តម្រឹមខាងចុង",
  "align-stretch": "តម្រឹមលាតសន្ធឹង",
  "auto-grow height": "កម្ពស់កើនឡើងស្វ័យប្រវត្តិ",
  "transform": "បំលែង",
  "layer order": "លំដាប់ជាន់",
  "rotation slider": "របាររំកិលបង្វិល",
  "visibility & state": "ភាពមើលឃើញ និងស្ថានភាព",
  "lock position": "ចាក់សោទីតាំង",
  "disable resizing and dragging": "បិទការប្ដូរទំហំ និងអូស",
  "hide on print": "លាក់ពេលបោះពុម្ព",
  "exclude this block from exports": "ដកប្លុកនេះចេញពីការនាំចេញ",
  "padding (offsets)": "ចន្លោះខាងក្នុង (Padding)",
  "top": "ខាងលើ",
  "right": "ខាងស្តាំ",
  "bottom": "ខាងក្រោម",
  "left": "ខាងឆ្វេង",
  "borders": "ស៊ុម",
  "bring to front": "នាំមកខាងមុខបង្អស់",
  "send to back": "ផ្ញើទៅក្រោយបង្អស់",
  "toggle lock": "ចាក់សោ / បើកសោ"
};

/**
 * Composable (reactive) – use this inside component setup() so that
 * `settingsStore.language` is a tracked reactive dependency and the
 * template re-renders automatically when the language changes.
 *
 * Usage:
 *   const { translateUi } = useTranslateUi()
 */
export function useTranslateUi() {
  const settingsStore = useSettingsStore();

  function translateUi(text) {
    if (typeof text !== "string") return text;

    // Access settingsStore.language here so Vue tracks it as a dependency
    if (settingsStore.language !== "kh") {
      return text;
    }

    const trimmed = text.trim();
    const lower = trimmed.toLowerCase();

    // Try exact lowercase match
    if (UI_TRANSLATIONS[lower]) {
      return UI_TRANSLATIONS[lower];
    }

    // Handle case with colon at the end
    if (trimmed.endsWith(":")) {
      const keyWithoutColon = trimmed.slice(0, -1).trim().toLowerCase();
      if (UI_TRANSLATIONS[keyWithoutColon]) {
        return UI_TRANSLATIONS[keyWithoutColon] + ":";
      }
    }

    return text;
  }

  return { translateUi };
}

/**
 * Plain (non-reactive) helper for use outside of component setup (e.g., in
 * non-Vue JS files). Changes to settingsStore.language will NOT cause
 * re-renders when using this version.
 */
export function translateUi(text) {
  const settingsStore = useSettingsStore();
  if (typeof text !== "string" || settingsStore.language !== "kh") return text;

  const trimmed = text.trim();
  const lower = trimmed.toLowerCase();
  if (UI_TRANSLATIONS[lower]) return UI_TRANSLATIONS[lower];
  if (trimmed.endsWith(":")) {
    const key = trimmed.slice(0, -1).trim().toLowerCase();
    if (UI_TRANSLATIONS[key]) return UI_TRANSLATIONS[key] + ":";
  }
  return text;
}
